### PR TITLE
fix: platform-specific dependencies are not shown

### LINKED ISSUE #36: Check cfg'd and target specific dependencies
For example `getrandom` has the following [`Cargo.toml`](https://github.com/rust-random/getrandom/blob/master/Cargo.toml), but on its [page](https://deps.rs/repo/github/rust-random/getrandom) only `log` crate is shown.

### LINKED ISSUE #232: Platform-specific dependencies are not shown
Besides the usual `[dependencies]`, `[dev-dependencies]` and `[build-dependencies]` sections, Cargo allows specifying [per-platform dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) with the following syntax:

```toml
[target.'cfg(windows)'.dependencies]
foo = "1.2.3"

[target.bar.dev-dependencies]
bar = "4.5.6"
```

The general syntax is `target.*.(dev-|build-)?dependencies`, where the middle part `*` may represent the platform in arbitrarily complex ways (`cfg()`, custom target, etc.).

Currently, such dependencies are not recognized by deps.rs, see [this example Cargo.toml](https://github.com/gendx/stv-rs/blob/main/Cargo.toml):

```toml
[target.'cfg(any(target_os = "android", target_os = "dragonfly", target_os = "freebsd", target_os = "linux"))'.dependencies]
nix = { version = "0.28", features = ["sched"] }
```

I don't think deps.rs should try to parse the platform part (to report for which platform there are outdated dependencies), but it would be good to report all the target-specific dependencies :)

### PR DESCRIPTION
**Pull request by lhenry-dev**
## Fix recognition of target-specific dependencies in `Cargo.toml`

This PR addresses the issue where `deps.rs` did not recognize target-specific dependencies defined using the `[target.*.(dev-|build-)?dependencies]` syntax in `Cargo.toml`.

Cargo allows specifying [per-platform dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) like so:
```toml
[target.'cfg(windows)'.dependencies]
foo = "1.2.3"

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
nix = { version = "0.28", features = ["sched"] }
```

Previously, these sections were ignored by `deps.rs`, which caused incomplete or inaccurate dependency reporting. With this fix, all target-specific dependencies are now properly collected and reported, regardless of the complexity of the platform specification.

Note: This change does not attempt to evaluate or parse the platform expressions themselves — it simply ensures that all such dependencies are included in the analysis output.

Related issues:
- Fixes #232 
- Fixes #36

### CODE REVIEW

File: src/parsers/manifest.rs [hunk 1]
```diff
@@ -32,6 +32,18 @@ struct CargoTomlWorkspace {
...
+pub struct CargoTomlTargetDependencies {
+    #[serde(default)]
+    dependencies: Option<IndexMap<String, CargoTomlDependency>>,
+    #[serde(rename = "dev-dependencies")]
+    #[serde(default)]
+    dev_dependencies: Option<IndexMap<String, CargoTomlDependency>>,
+    #[serde(rename = "build-dependencies")]
+    #[serde(default)]
+    build_dependencies: Option<IndexMap<String, CargoTomlDependency>>,
+}
```
Comment (tguichaoua) [inline src/parsers/manifest.rs:45]: You don't need `Option`s here, `#[serde(default)]` will returns an empty `IndexMap`

**Review by tguichaoua — APPROVED** [review]
LGTM

**Review by robjtede — APPROVED** [review]
